version: "3"

    
services:
  config-server:
    build:
      context: ./config-server
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M

  sensor-emails-provider:
    build:
      context: ./sensor-emails-provider
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  sensor-range-provider:
    build:
      context: ./sensor-range-provider
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  admin-console:
    build:
      context: ./admin-console
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - STREAM_API_SECRET=${STREAM_API_SECRET}

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - RANGE_PROVIDER_HOST=sensor-range-provider

  avg-populator:
    build:
      context: ./avg-populator
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  avg-reducer:
    build:
      context: ./avg-reducer
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  email-notifier:
    build:
      context: ./email-notifier
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - STREAM_API_SECRET=${STREAM_API_SECRET}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - EMAILS_PROVIDER_HOST=sensor-emails-provider
      
  account-provider:
    build:
      context: ./account-provider
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - ACCOUNT_PROVIDER_HOST=account-provider
      - MONGO_PASSWORD=${MONGO_PASSWORD}

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
      args:
        VERSION: "0.0.2"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 300M
        reservations:
          cpus: '0.3'
          memory: 250M
    environment:
      - ACCOUNT_PROVIDER_HOST=account-provider
      - ADMIN_CONSOLE_HOST=admin-console
      - EMAILS_PROVIDER_HOST=sensor-emails-provider
      - RANGE_PROVIDER_HOST=sensor-range-provider
    ports:
      - 9595:9595